Staging
weeve-modules/translator pull request #1
Opened 2022-04-06 13:27 UTC by mesudpasic

2022-05-02 11:37 UTC, kubagrzelak requested changes

2022-05-02 11:37 UTC, kubagrzelak commented on Module.yaml
> +name: Translator Module
Please remove word "Module"

2022-05-02 11:37 UTC, kubagrzelak commented on Module.yaml
> +    name: Translator
Please change category to `Policies`

2022-05-02 11:37 UTC, kubagrzelak commented on Module.yaml
> +    name: Port
Please remove this.

2022-05-02 11:37 UTC, kubagrzelak commented on README.md
> +# Translator Module
Please remove word "Module"

2022-05-02 11:37 UTC, kubagrzelak commented on README.md
> +| Name           | Translator Module           |
Please remove word "Module"

2022-05-02 11:37 UTC, kubagrzelak commented on README.md
> +- [MQTT Ingress](#translator-module)
Please change MQTT Ingress -> Translator and remove word "Module" from the brackets

2022-05-02 11:37 UTC, kubagrzelak commented on README.md
> +Encoder for Vicki LoRaWAN's commands.
Please be more descriptive and informative. I have no idea what this module does by reading this sentence.

2022-05-02 11:37 UTC, kubagrzelak commented on README.md
> +- DEVICE_MANUFACTURER
By Environmental Variables we mean the variables that are set by a user in the UI (so the ones from YAML file). Please construct a table similar to the tables in the same section of McClimate Vicki Encoder: https://github.com/weeve-modules/mcclimate-vicki-encoder/blob/main/README.md

2022-05-02 11:37 UTC, kubagrzelak commented on README.md
> +| DEVICE_MANUFACTURER | string | Name of the device manufacturer that will map to JSON file where mapping is read for commands and parameters |
Please remove this entry, as it should be mentioned above in Environmental Variables table as per my previous comment.

2022-05-02 11:37 UTC, kubagrzelak commented on README.md
> +- Module translates JSON command input from MongoDB (application) to compatible command interface for specific device, so that encoder module can convert it to valid command
This is a good sentence that should be moved to Description section

2022-05-02 11:37 UTC, kubagrzelak commented on docker-compose.yml
> +      INGRESS_PORT: 80
Please add all environmental variables that are set in the UI (the ones from the YAML file) and provide their examples, so someone calling docker compose command could run this file.

2022-05-02 11:37 UTC, kubagrzelak commented on docker-compose.yml
> +  translator_service:
please change translator_service to translator (name of the module)

2022-05-02 11:37 UTC, kubagrzelak commented on docker-compose.yml
> +      MODULE_NAME: translator_service
please change translator_service to translator (name of the module)

2022-05-02 11:37 UTC, kubagrzelak commented on image/src/config/config.js
> +  MODULE_NAME: env('MODULE_NAME', 'Translator Module'),
Please change MODULE_NAME to `translator`

2022-05-02 11:37 UTC, kubagrzelak commented on image/src/utils/util.js
> +const { NESTED_RESPONSE, CUSTOM_FIELDS } = require('../config/config')
If we don't use NESTED_RESPONSE or CUSTOME_FIELDS then please remove this line

2022-05-02 14:23 UTC, mesudpasic commented on Module.yaml
> +name: Translator Module
done

2022-05-02 14:23 UTC, mesudpasic commented on Module.yaml
> +    name: Translator
done

2022-05-02 14:24 UTC, mesudpasic commented on Module.yaml
> +    name: Port
done

2022-05-02 14:25 UTC, mesudpasic commented on README.md
> +# Translator Module
done

2022-05-02 14:25 UTC, mesudpasic commented on README.md
> +| Name           | Translator Module           |
done

2022-05-02 14:26 UTC, mesudpasic commented on README.md
> +- [MQTT Ingress](#translator-module)
done

2022-05-02 14:28 UTC, mesudpasic commented on README.md
> +Encoder for Vicki LoRaWAN's commands.
done.

2022-05-02 14:29 UTC, mesudpasic commented on README.md
> +- DEVICE_MANUFACTURER
done.

2022-05-02 14:32 UTC, mesudpasic commented on README.md
> +- Module translates JSON command input from MongoDB (application) to compatible command interface for specific device, so that encoder module can convert it to valid command
done

2022-05-02 14:32 UTC, mesudpasic commented on README.md
> +| DEVICE_MANUFACTURER | string | Name of the device manufacturer that will map to JSON file where mapping is read for commands and parameters |
done

2022-05-02 14:32 UTC, mesudpasic commented on docker-compose.yml
> +      INGRESS_PORT: 80
added DEVICE_MANUFACTURER

2022-05-02 14:32 UTC, mesudpasic commented on docker-compose.yml
> +  translator_service:
done

2022-05-02 14:32 UTC, mesudpasic commented on docker-compose.yml
> +      MODULE_NAME: translator_service
done

2022-05-02 14:33 UTC, mesudpasic commented on image/src/config/config.js
> +  MODULE_NAME: env('MODULE_NAME', 'Translator Module'),
done

2022-05-02 14:33 UTC, mesudpasic commented on image/src/utils/util.js
> +const { NESTED_RESPONSE, CUSTOM_FIELDS } = require('../config/config')
removed

2022-05-03 08:44 UTC, kubagrzelak approved these changes

2022-05-03 08:44 UTC, merged